### ISSUE TITLE
[BUG] Calibre not reachable - Closing connection with error:  Error: WS was inactive for too long

### ISSUE THREAD

**Issue by DunklerPhoenix** [linuxserver/docker-calibre#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The calibre container throws the error "Closing connection with error:  Error: WS was inactive for too long" and is not reachable over the ports

### Steps To Reproduce

1. Use the command from this comment: https://github.com/linuxserver/docker-calibre/issues/104#issuecomment-1267439699
2. see the error

### Environment

```markdown
- OS:
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-19-amd64
      Architecture: x86-64
- How docker service was installed: via apt
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --rm --name test -p 8080:8080 --security-opt seccomp=unconfined lscr.io/linuxserver/calibre
```

### Container logs

```bash
https://gist.github.com/DunklerPhoenix/9b32872e2b0cef17d65d4f50f33cdd46

(Too long for this field)
```

**Comment by DunklerPhoenix** [comment]
Process inside Container:
```

UID | PID | PPID | C | STIME | TTY | TIME | CMD
-- | -- | -- | -- | -- | -- | -- | --
root | 2871883 | 2871862 | 0 | 22:40 | ? | 00:00:00 | /package/admin/s6/command/s6-svscan -d4 -- /run/service
root | 2871963 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise s6-linux-init-shutdownd
root | 2871964 | 2871963 | 0 | 22:40 | ? | 00:00:00 | /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
root | 2871989 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise svc-autostart
root | 2871990 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise svc-xrdp
root | 2871991 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise s6rc-oneshot-runner
root | 2871992 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise s6rc-fdholder
root | 2871993 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise svc-web
root | 2871994 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise svc-xrdp-sesman
root | 2871995 | 2871883 | 0 | 22:40 | ? | 00:00:00 | s6-supervise svc-guacd
root | 2872003 | 2871991 | 0 | 22:40 | ? | 00:00:00 | /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --
root | 2872407 | 2871994 | 0 | 22:40 | ? | 00:00:00 | /usr/sbin/xrdp-sesman --nodaemon
root | 2872418 | 2871990 | 0 | 22:41 | ? | 00:00:00 | /usr/sbin/xrdp --nodaemon
root | 2872450 | 2871995 | 0 | 22:41 | ? | 00:00:00 | /usr/sbin/guacd -f -b 0.0.0.0 -l 4822
911 | 2872461 | 2871993 | 0 | 22:41 | ? | 00:00:00 | node app.js
root | 2872512 | 2871989 | 0 | 22:41 | ? | 00:00:00 | bash ./run
root | 2872657 | 2872407 | 0 | 22:41 | ? | 00:00:00 | /usr/sbin/xrdp-sesman --nodaemon
911 | 2872658 | 2872657 | 0 | 22:41 | ? | 00:00:00 | /usr/bin/openbox --startup /usr/lib/x86_64-linux-gnu/openbox-autostart OPENBOX
911 | 2872659 | 2872657 | 0 | 22:41 | ? | 00:00:00 | /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
911 | 2872666 | 2872657 | 0 | 22:41 | ? | 00:00:00 | /usr/sbin/xrdp-chansrv
911 | 2872701 | 2871883 | 0 | 22:41 | ? | 00:00:00 | /usr/bin/dbus-launch --exit-with-session --sh-syntax
911 | 2872702 | 2871883 | 0 | 22:41 | ? | 00:00:00 | /usr/bin/dbus-daemon --syslog --fork --print-pid 5 --print-address 7 --session
911 | 2872713 | 2872658 | 0 | 22:41 | ? | 00:00:00 | /usr/bin/ssh-agent x-session-manager
911 | 2872729 | 2872658 | 0 | 22:41 | ? | 00:00:00 | /bin/sh /usr/lib/x86_64-linux-gnu/openbox-autostart OPENBOX
911 | 2872734 | 2872729 | 0 | 22:41 | ? | 00:00:00 | sh /config/.config/openbox/autostart
911 | 2872735 | 2872734 | 0 | 22:41 | ? | 00:00:00 | /opt/calibre/bin/calibre
root | 2872858 | 2872512 | 0 | 22:41 | ? | 00:00:00 | sleep infinity

```

Inspect:


```
{
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/config",
            "LANGUAGE=en_US.UTF-8",
            "LANG=en_US.UTF-8",
            "TERM=xterm",
            "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
            "S6_VERBOSITY=1",
            "S6_STAGE2_HOOK=/docker-mods",
            "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
            "LSIO_FIRST_PARTY=true",
            "CUSTOM_PORT=8080",
            "GUIAUTOSTART=true",
            "TITLE=Calibre"
        ],
        "ExposedPorts": {
            "3000/tcp": {},
            "3389/tcp": {},
            "8080/tcp": {}
        },
        "Hostname": "e4bf16fd2898",
        "Image": "lscr.io/linuxserver/calibre",
        "Labels": {
            "build_version": "Linuxserver.io version:- v6.14.0-ls206 Build-date:- 2023-03-10T03:24:58+01:00",
            "maintainer": "aptalca",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2023-03-10T03:24:58+01:00",
            "org.opencontainers.image.description": "[Calibre](https://calibre-ebook.com/) is a powerful and easy to use e-book manager. Users say it’s outstanding and a must-have. It’ll allow you to do nearly everything and it takes things a step beyond normal e-book software. It’s also completely free and open source and great for both casual users and computer experts.",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-calibre",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "2587221f5e63d3b5af40c0ecbd4e4852069f268b",
            "org.opencontainers.image.revision": "2587221f5e63d3b5af40c0ecbd4e4852069f268b",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-calibre",
            "org.opencontainers.image.title": "Calibre",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-calibre/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "v6.14.0-ls206"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/config": {}
        },
        "WorkingDir": "/"
    },
    "Created": "2023-03-14T21:40:32.042007236Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/efbb9cb359606a34ab0d5d0cf03f0088033c68fca4aea4b493b80c6e6dde75ba-init/diff:/var/lib/docker/overlay2/96839963712c59db5b2c1ef1adaf2d2659993b10fef6900b6d5e15ca73b29fe7/diff:/var/lib/docker/overlay2/5826c0c0a4153d1b4c0a5ea6ce70fdfcb743810f4b3f7dde15481d21ea850277/diff:/var/lib/docker/overlay2/eefa395e96f4b67af14f8481110254283cc3d501a883989d244f71d9b3776c71/diff:/var/lib/docker/overlay2/b1604cbfa622dad45d218d555b6b669a39539e59e5fee2fabf125ec530367468/diff:/var/lib/docker/overlay2/e78ed864dd7c508e7bade8be886c478e50eacecd84ed0e5d172ab7ecc8a5bc84/diff:/var/lib/docker/overlay2/ddeca039d99d4695af93c7470d621af138f5b99e6532da0caaab8452f4732310/diff:/var/lib/docker/overlay2/a34561b7f7d4a47b916a8ca2227d3f03c5079cb792ea421111f82dbe26b67ca1/diff:/var/lib/docker/overlay2/2180db54cab0e0e31cdf0262a2c745d7a9bf1a627a9869131eb4803e70d60a43/diff:/var/lib/docker/overlay2/fe7d839a464d21223a629c537933b08c06921227be5f5c95be229ef277ab5ad7/diff:/var/lib/docker/overlay2/a84012eb0133ea5b4d0e2391ba868f4cf86ed8de33822cfa35fab69e7ba3f678/diff:/var/lib/docker/overlay2/f474b0411e2a69302554490adc2fa8cf48a9046ff182341c8009d86c4e7eecd6/diff:/var/lib/docker/overlay2/e141d17c190a328f823fd55c6a9d96fb816c7b1edccd36829accb523ccfea21e/diff:/var/lib/docker/overlay2/c3c82664cf4d264ec4078a3fe206ce886f55516f616cabe855c25b6f2be1c6a0/diff:/var/lib/docker/overlay2/8ab745eb79b2ef8d56a719aa7874374b88f4b8da32096071ec519ba7f44d1788/diff:/var/lib/docker/overlay2/183dda66d1fa24cc202b5bada38cff3d28067fb0ff7c4d1630ebfdbcee07d593/diff",
            "MergedDir": "/var/lib/docker/overlay2/efbb9cb359606a34ab0d5d0cf03f0088033c68fca4aea4b493b80c6e6dde75ba/merged",
            "UpperDir": "/var/lib/docker/overlay2/efbb9cb359606a34ab0d5d0cf03f0088033c68fca4aea4b493b80c6e6dde75ba/diff",
            "WorkDir": "/var/lib/docker/overlay2/efbb9cb359606a34ab0d5d0cf03f0088033c68fca4aea4b493b80c6e6dde75ba/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": true,
        "Binds": null,
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "private",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "default",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8080"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "Runtime": "runc",
        "SecurityOpt": [
            "seccomp=unconfined"
        ],
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999/hostname",
    "HostsPath": "/var/lib/docker/containers/e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999/hosts",
    "Id": "e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999",
    "Image": "sha256:a3cca556dd6a3b5f186119ef30ab69e61f8b60902083748ecbdb4fac1d3a5618",
    "LogPath": "/var/lib/docker/containers/e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999/e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Driver": "local",
            "Mode": "",
            "Name": "86ba9994c39e64e53541c386d83f7737dd5cd013a403f6ecc20204ed59a21090",
            "Propagation": "",
            "RW": true,
            "Source": "/var/lib/docker/volumes/86ba9994c39e64e53541c386d83f7737dd5cd013a403f6ecc20204ed59a21090/_data",
            "Type": "volume"
        }
    ],
    "Name": "/test",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "d467045e0ba408470924f75f1ddd7f583d59ee721df7b63f548435562327336a",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "d467045e0ba408470924f75f1ddd7f583d59ee721df7b63f548435562327336a",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:02",
                "NetworkID": "b1b8f3eaa9b3ebb85a03d3f31b468b88fa57c954d7298f98a5b4c5c49dd780be"
            }
        },
        "Ports": {
            "3000/tcp": null,
            "3389/tcp": null,
            "8080/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8080"
                }
            ]
        },
        "SandboxID": "b37e4a217592f21ff96e2b2b21855f0b78120f043874c131bfe8a229454fea0b",
        "SandboxKey": "/var/run/docker/netns/b37e4a217592",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/e4bf16fd289843229cccf61d82c2fee8a0e55bb8e2a47c80b9257fdcf1644999/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 2871883,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2023-03-14T21:40:33.229586645Z",
        "Status": "running"
    }
}
```

**Comment by jradwan** [comment]
I'm seeing the same issue using the latest container on my Synology NAS (DSM 7). Log snippet:

```Starting guacamole-lite websocket server
listening on *:8080
xrdp[215]: [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed

xrdp[215]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed

xrdp[215]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed

xrdp[215]: [ERROR] xrdp_iso_send: trans_write_copy_s failed

[guac-init] Auto start set, starting application
xrdp[215]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[2023-03-31 17:02:24] [Connection 1]  Client connection open
[2023-03-31 17:02:24] [Connection 1]  Opening guacd connection
[2023-03-31 17:02:24] [Connection 1]  guacd connection open
[2023-03-31 17:02:24] [Connection 1]  Selecting connection type: rdp
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 6.select,3.rdp;
guacd[210]: INFO:	Creating new client for protocol "rdp"
guacd[210]: INFO:	Connection ID is "$043ab8c2-b3c5-403d-be3a-22904ab807cf"
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 4.size,4.1024,3.768,2.96;
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 5.video;
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 5.image;
[2023-03-31 17:02:24] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2023-03-31 17:02:24] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1024,3.768,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
guacd[251]: INFO:	Security mode: Negotiate (ANY)
guacd[251]: INFO:	Resize method: none
guacd[251]: INFO:	User "@e9049627-8459-4315-af13-9b55ab0bcc81" joined connection "$043ab8c2-b3c5-403d-be3a-22904ab807cf" (1 users now present)
5.ready,37.$043ab8c2-b3c5-403d-be3a-22904ab807cf;
guacd[251]: INFO:	Loading keymap "base"
guacd[251]: INFO:	Loading keymap "en-us-qwerty"
[ls.io-init] done.
5.audio,1.1,31.audio/L16;rate=44100,channels=2;4.size,1.0,4.1024,3.768;4.size,2.-1,2.11,2.16;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,232.iVBORw0KGgoAAAANSUhEUgAAAAsAAAAQCAYAAADAvYV+AAAABmJLR0QA/wD/AP+gvaeTAAAAYklEQVQokY2RQQ4AIQgDW+L/v9y9qCEsIJ4QZggoJAnDYwAwFQwASI4EO8FEMH95CRYTnfCDOyGFK6GEM6GFo7AqKI4sSSsCJH1X+roFkKdjueABX/On77lz2uGtr6pj9okfTeJQAYVaxnMAAAAASUVORK5CYII=;3.end,1.3;6.cursor,1.0,1.0,2.-1,1.0,1.0,2.11,2.16;
xrdp[199]: [INFO ] Socket 11: AF_INET6 connection received from ::ffff:127.0.0.1 port 55644

xrdp[280]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem

xrdp[280]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem

xrdp[280]: [INFO ] Connected client computer name: Guacamole RDP

xrdp[280]: [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)

xrdp[280]: [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)

xrdp[280]: [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000409]

xrdp[280]: [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []

xrdp[280]: [INFO ] TLS connection established from ::ffff:127.0.0.1 port 55644: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384

[2023-03-31 17:02:34] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2023-03-31 17:02:34] [Connection 1]  Closing guacd connection
[2023-03-31 17:02:34] [Connection 1]  Client connection closed```

**Comment by jradwan** [comment]
I had this issue with:

Linuxserver.io version:- v6.14.1-ls207 Build-date:- 2023-03-15T22:02:06-05:00

but it seems to be fixed with:

Linuxserver.io version:- v6.14.1-ls208 Build-date:- 2023-03-25T22:24:40-05:00

**Comment by BoKKeR** [comment]
I get the same problem on both builds

**Comment by DunklerPhoenix** [comment]
Can't confirm
Problem still exists with v6.14.1-ls208 and also with v6.14.1-ls209

**Comment by DunklerPhoenix** [comment]
Command:
`docker run -d --rm --name test -p 8079:8080 --security-opt seccomp=unconfined lscr.io/linuxserver/calibre:v6.14.1-ls208
`
Logs:
```
[2023-04-02 14:58:08] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2023-04-02 14:58:08] [Connection 1]  Closing guacd connection
[2023-04-02 14:58:08] [Connection 1]  Client connection closed
guacd[259]: ERROR:	User is not responding.
guacd[259]: INFO:	User "@5b87d480-f6d1-4e65-90fe-a18dde88eb78" disconnected (0 users remain)
guacd[259]: INFO:	Last user of connection "$812cc47c-605b-4e64-9260-fadbc397ebae" disconnected
guacd[259]: INFO:	Internal RDP client disconnected
guacd[205]: INFO:	Connection "$812cc47c-605b-4e64-9260-fadbc397ebae" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x564920db0700
```

**Comment by DunklerPhoenix** [comment]
I also tried with the portainer templates from pi-hosted
https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/template/portainer-v2-amd64.json

Still same error

**Comment by BoKKeR** [comment]
The latest one works for me, here is my setup: 

https://i.imgur.com/MnYhlBD.png

**Comment by DunklerPhoenix** [comment]
I think i'm waiting for the pull request https://github.com/linuxserver/docker-calibre/pull/122

It looks good for that problem

**Comment by DunklerPhoenix** [comment]
Irrelevant with new base
