### ISSUE TITLE
[BUG] GUI not loading with Docker Compose / Synology DSM 7 

### ISSUE THREAD

**Issue by rondobohrens** [linuxserver/docker-calibre#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The docker container spins up without problems. When navigating to the specified http/s port, KASM VNC loads, but the calibre GUI is not shown. 

The logs show import problems for QT6 modules. 

### Expected Behavior

The calibre GUI appears when navigating to the specified http/s port. 

### Steps To Reproduce

1. Spin up docker-compose with `docker-compose up -d`
2. Navigate to http://[NAS-ip]:/[http-port]
3. See black screen.

### Environment

```markdown
- OS: DSM 7 Synology 
- Model: Synology DS916+; Intel Pentium N3710
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
    volumes:
      - $DOCKERDIR/app_data/calibre:/config
    ports:
      - "$CALIBRE_HTTP:8080"
      - "$CALIBRE_HTTPS:8181"
      - "$CALIBRE_WEB:8081"
    restart: unless-stopped
```

### Container logs

```bash
16.02.2024
17:29:35
[migrations] started
16.02.2024
17:29:35
[migrations] no migrations found
16.02.2024
17:29:39
───────────────────────────────────────
16.02.2024
17:29:39
16.02.2024
17:29:39
      ██╗     ███████╗██╗ ██████╗
16.02.2024
17:29:39
      ██║     ██╔════╝██║██╔═══██╗
16.02.2024
17:29:39
      ██║     ███████╗██║██║   ██║
16.02.2024
17:29:39
      ██║     ╚════██║██║██║   ██║
16.02.2024
17:29:39
      ███████╗███████║██║╚██████╔╝
16.02.2024
17:29:39
      ╚══════╝╚══════╝╚═╝ ╚═════╝
16.02.2024
17:29:39
16.02.2024
17:29:39
   Brought to you by linuxserver.io
16.02.2024
17:29:39
───────────────────────────────────────
16.02.2024
17:29:39
16.02.2024
17:29:39
To support LSIO projects visit:
16.02.2024
17:29:39
https://www.linuxserver.io/donate/
16.02.2024
17:29:39
16.02.2024
17:29:39
───────────────────────────────────────
16.02.2024
17:29:39
GID/UID
16.02.2024
17:29:39
───────────────────────────────────────
16.02.2024
17:29:39
16.02.2024
17:29:39
User UID:    1026
16.02.2024
17:29:39
User GID:    100
16.02.2024
17:29:39
───────────────────────────────────────
16.02.2024
17:29:39
16.02.2024
17:29:40
[custom-init] No custom files found, skipping...
16.02.2024
17:29:40
[ls.io-init] done.
16.02.2024
17:29:41
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
16.02.2024
17:29:45
16.02.2024
17:29:45
Xvnc KasmVNC 1.2.0 - built Feb 13 2024 23:14:23
16.02.2024
17:29:45
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
16.02.2024
17:29:45
See http://kasmweb.com for information on KasmVNC.
16.02.2024
17:29:45
Underlying X server release 12014000, The X.Org Foundation
16.02.2024
17:29:45
16.02.2024
17:29:46
Obt-Message: Xinerama extension is not present on the server
16.02.2024
17:29:47
shared memfd open() failed: Function not implemented
16.02.2024
17:29:53
Failed to import PyQt module: PyQt6.QtCore with error: libQt6Core.so.6: cannot open shared object file: No such file or directory
16.02.2024
17:29:53
Traceback (most recent call last):
16.02.2024
17:29:53
  File "runpy.py", line 198, in _run_module_as_main
16.02.2024
17:29:53
  File "runpy.py", line 88, in _run_code
16.02.2024
17:29:53
  File "site.py", line 47, in <module>
16.02.2024
17:29:53
  File "site.py", line 43, in main
16.02.2024
17:29:53
  File "calibre/gui_launch.py", line 70, in calibre
16.02.2024
17:29:53
  File "calibre/gui_launch.py", line 35, in setup_qt_logging
16.02.2024
17:29:53
ImportError: cannot import name 'QLoggingCategory' from 'qt.core' (/opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)
16.02.2024
17:29:55
shared memfd open() failed: Function not implemented
16.02.2024
17:29:56
shared memfd open() failed: Function not implemented
16.02.2024
17:30:55
 2024-02-16 18:30:55,882 [INFO] websocket 0: got client connection from 127.0.0.1
16.02.2024
17:30:55
 2024-02-16 18:30:55,939 [PRIO] Connections: accepted: @192.168.90.1_1708104655.914237::websocket
16.02.2024
17:31:34
 2024-02-16 18:31:34,373 [PRIO] Connections: closed: @192.168.90.1_1708104655.914237::websocket (Clean disconnection)
```

**Comment by j0nnymoe** [comment]
This is likely due to the QT6 modules requiring certain kernel modules that isn't included on your Synology kernel version. Could you post your kernel info please?

**Comment by rondobohrens** [comment]
Thank you. Currently I am on kernel version 3.10.108.

If this is too old, best course of action would be to downgrade to a v4 tag with QT5?

**Comment by Unessential** [comment]
Same thing is happening to me on Unraid as well.

**Comment by thelamer** [comment]
> Thank you. Currently I am on kernel version 3.10.108.
> 
> If this is too old, best course of action would be to downgrade to a v4 tag with QT5?

Your kernel is from 2013, just an interesting fun fact.

**Comment by Unessential** [comment]
using a tag of the older stable version worked for me, likely a recent change.

**Comment by cuksi** [comment]
What older version did you use ? I tried few different versions and is not working on my Synology NAS.

**Comment by ralphh78** [comment]
The last version I have running is 5.9.0. I hope this can be fixed.

**Comment by thespad** [comment]
It's not something we can fix, the Synology 3.x kernel doesn't support the necessary functionality for the qt6 components that Calibre is now using.
