### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by sse450** [linuxserver/docker-calibre#19]
## Expected Behavior
It should be possible to enter non-ascii characters in Title, Author, Comments etc.

## Current Behavior
Calibre doesn't print any non-ascii character. If the book is already imported "with" non-ascii characters, then Calibre displays them without any problem. But, if you want to edit by entering non-ascii characters, Calibre doesn't accept. If a text including non-ascii character is copied/pasted within Calibre, it just deletes non-ascii characters, and displays others. Standalone installation (not docker) doesn't exhibit this problem.

## Steps to Reproduce
1. Install the Calibre docker
2. Import at least an ebook into the library
3. Try to copy-paste/enter these characters: şğüöıç in any Calibre field
4. You will see that Calibre will not display them

## Environment
**OS:**      Unraid
**CPU architecture:** x86_64
**How docker service was installed:**      
I installed the docker using the Calibre docker template for Unraid.

## Command used to create docker container (run/create/compose/screenshot)
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='calibre' --net='proxynet' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="Europe/Moscow" -e HOST_OS="Unraid" -e 'GUAC_USER'='sse450' -e 'GUAC_PASS'='d4bedc722cbee8ec14be722bce9a45' -e 'PUID'='99' -e 'PGID'='100' -p '9080:8080/tcp' -p '9081:8081/tcp' -v '/mnt/user/books/':'/books':'rw' -v '/mnt/user/downloads/complete/books-pre/':'/import':'rw' -v '/mnt/user/appdata/calibre':'/config':'rw' 'linuxserver/calibre' 

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 11-moduser: executing... 
[cont-init.d] 11-moduser: exited 0.
[cont-init.d] 12-prep_xrdp: executing... 
[cont-init.d] 12-prep_xrdp: exited 0.
[cont-init.d] 13-update_app_name: executing... 
[cont-init.d] 13-update_app_name: exited 0.
[cont-init.d] 14-configure_openbox: executing... 
[cont-init.d] 14-configure_openbox: exited 0.
[cont-init.d] 30-update_webapp_context: executing... 
[cont-init.d] 30-update_webapp_context: exited 0.
[cont-init.d] 35-update_guac_creds: executing... 
[cont-init.d] 35-update_guac_creds: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Unable to find an X display. Ensure you have permission to connect to the display.

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-148-generic x86_64 Ubuntu
Current Operating System: Linux b4552a1d0fa3 4.19.56-Unraid #1 SMP Tue Jun 25 10:19:34 PDT 2019 x86_64
Kernel command line: BOOT_IMAGE=/bzimage vfio-pci.ids=8086:1521 initrd=/bzroot,/bzroot-gui 
Build Date: 03 June 2019  08:10:35AM
xorg-server 2:1.19.6-1ubuntu4.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.pid-428.log", Time: Tue Dec 10 14:02:47 2019
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
guacd[433]: INFO:	Guacamole proxy daemon (guacd) version 0.9.14 started
guacd[433]: INFO:	Listening on host 127.0.0.1, port 4822
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x154698b9b010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x00050654 bx 0x03100800 cx 0x7ffefbff dx 0xbfebfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpXvInit: depth 24
rdpClientConInit: kill disconnected [0] timeout [0] sec

rdpScreenInit: out
rdpmousePreInit: drv 0x5633819723f0 info 0x563381b0ca50, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x154698f74c60
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x56338197e270 info 0x563381c7d670, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x154698d71530
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpSaveScreen:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
Warning: Cannot convert string "-*-helvetica-bold-r-normal--*-120-*-*-*-*-iso8859-1" to type FontStruct
Warning: Cannot convert string "-*-courier-medium-r-normal--*-120-*-*-*-*-iso8859-1" to type FontStruct
rdpInDeferredUpdateCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[433]: INFO:	Guacamole connection closed during handshake
rdpRRGetInfo:
Obt-Message: Xinerama extension is not present on the server
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
rdpRRGetInfo:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
10-Dec-2019 17:02:51.012 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with JAR file [/usr/share/tomcat8/lib/commons-dbcp.jar], exists: [false], canRead: [false]
10-Dec-2019 17:02:51.017 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with JAR file [/usr/share/tomcat8/lib/commons-pool.jar], exists: [false], canRead: [false]
10-Dec-2019 17:02:51.022 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.022 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.023 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.023 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.027 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.027 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.028 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.028 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.029 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.029 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.030 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.030 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
10-Dec-2019 17:02:51.126 SEVERE [main] org.apache.catalina.startup.Catalina.initDirs Cannot find specified temporary folder at [/var/lib/tomcat8/temp]
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 181, resource id: 0, major code: 140 (Unknown), minor code: 20
10-Dec-2019 17:02:51.738 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
10-Dec-2019 17:02:51.739 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
10-Dec-2019 17:02:51.739 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
10-Dec-2019 17:02:51.739 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
10-Dec-2019 17:02:51.740 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.19.56-Unraid
10-Dec-2019 17:02:51.740 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
10-Dec-2019 17:02:51.740 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
10-Dec-2019 17:02:51.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.4+11-post-Ubuntu-1ubuntu218.04.3
10-Dec-2019 17:02:51.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
10-Dec-2019 17:02:51.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
10-Dec-2019 17:02:51.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
10-Dec-2019 17:02:51.742 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
10-Dec-2019 17:02:51.742 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
10-Dec-2019 17:02:51.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
10-Dec-2019 17:02:51.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
10-Dec-2019 17:02:51.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
10-Dec-2019 17:02:51.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
10-Dec-2019 17:02:51.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/var/lib/tomcat8/temp
10-Dec-2019 17:02:51.745 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
10-Dec-2019 17:02:51.806 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
10-Dec-2019 17:02:51.826 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
10-Dec-2019 17:02:51.844 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 719 ms
10-Dec-2019 17:02:51.913 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
10-Dec-2019 17:02:51.913 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
10-Dec-2019 17:02:51.945 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/var/lib/tomcat8/webapps/ROOT.war]
10-Dec-2019 17:02:53.900 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17:02:54.427 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
17:02:54.531 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
17:02:54.694 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
17:02:54.842 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
10-Dec-2019 17:02:55.192 WARNING [localhost-startStop-1] com.google.inject.internal.ProxyFactory.<init> Method [public void org.apache.guacamole.rest.user.UserResource.updateObject(java.lang.Object) throws org.apache.guacamole.GuacamoleException] is synthetic and is being intercepted by [org.apache.guacamole.rest.RESTExceptionWrapper@50e8c1c5]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
10-Dec-2019 17:02:55.385 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
10-Dec-2019 17:02:55.386 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
10-Dec-2019 17:02:55.386 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
10-Dec-2019 17:02:55.386 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
10-Dec-2019 17:02:55.387 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
10-Dec-2019 17:02:55.387 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
10-Dec-2019 17:02:55.391 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
10-Dec-2019 17:02:55.489 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
10-Dec-2019 17:02:56.139 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
10-Dec-2019 17:02:56.146 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
10-Dec-2019 17:02:56.147 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
10-Dec-2019 17:02:56.152 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
10-Dec-2019 17:02:56.154 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
10-Dec-2019 17:02:56.173 INFO [localhost-startStop-1] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
10-Dec-2019 17:02:56.194 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/var/lib/tomcat8/webapps/ROOT.war] has finished in [4,248] ms
10-Dec-2019 17:02:56.198 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
10-Dec-2019 17:02:56.220 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 4375 ms
DBusExport: Failed to connect to DBUS session bus, with error: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "site-packages/calibre/gui2/notify.py", line 159, in get_notifier
  File "site-packages/calibre/gui2/notify.py", line 89, in get_dbus_notifier
  File "site-packages/dbus/_dbus.py", line 211, in __new__
  File "site-packages/dbus/_dbus.py", line 100, in __new__
  File "site-packages/dbus/bus.py", line 122, in __new__
DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

**Comment by sse450** [comment]
I think this is a guac keymap for RDP problem. guac 1.0 added some more keymaps. Is there any ETA for a new Calibre docker with guac 1.0?

**Comment by XPOHUK** [comment]
Same problem with Russian keyboard layout

**Comment by Trottel** [comment]
Same proble with Czech layout :(

**Comment by TUISTERa** [comment]
Same problem with Bulgarian layout. And not only the layout , i edin book metadata, i copy the title which is already in cyrillic and i paste it - it does not

**Comment by facorazza** [comment]
Up

**Comment by CHBMB** [comment]
> Up

It's not a forum.  (Where it's often considered rude to bump issues) What is the point?

**Comment by emiliogonzalezjunior** [comment]
I facing the same problem, using a US qwerty keyboard with calibre through a docker in unraid .

**Comment by triagony** [comment]
Don't know if it's the same problem but I cannot write german umlauts into calibre gui.

**Comment by emiliogonzalezjunior** [comment]
The probl

> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

The problem persist

**Comment by marapavelka** [comment]
Yes, it still persist and not single comment from devs :(

**Comment by ask0n** [comment]
Most probably this problem has nothing to do with calibre itself. Calibre image built on top of `lsiobase/guacgui` (https://github.com/linuxserver/docker-baseimage-guacgui)
Guacamole has this inside of their documentation:
```
Be sure to specify the URIEncoding="UTF-8" attribute as above to ensure that connection names, user names, etc. are properly received by the web application. If you will be creating connections that have Cyrillic, Chinese, Japanese, or other non-Latin characters in their names or parameter values, this attribute is required.
```

**Comment by alexandery** [comment]
@ask0n The only mentioning of "URIEncoding" I managed to find is the same as you've quoted here (https://guacamole.apache.org/doc/gug/proxying-guacamole.html) talks about non-ascii connection properties, but not the support of non-ascii characters typed into a hosted app. Care to elaborate on a solution?

**Comment by aptalca** [comment]
Is this still an issue with the new baseimage?

**Comment by marapavelka** [comment]
Yes, it's still an issue for Czech language. Although we can get around the situation by pasting through the clipboard now, but that's inconvenient and annoying because in Czech almost every word contains diacritics.

**Comment by azhiltsov** [comment]
I have tried to start it with env variable GUAC_KEYBOARD_LAYOUT=ru-ru-qwerty
It didn't help.
The clipboard workaround somehow is unavailable to me. Clipboard is always empty.

**Comment by ecser99** [comment]
It is still an issue for Hungarian language.  Also it is not possibel to paste special chars from the clipboard (CTRL-V). Is an env veriable GUAC_KEYBOARD_LAYOUT=hu-hu-qwertz possible?

**Comment by thelamer** [comment]
See here for more information: 
https://github.com/linuxserver/docker-webtop/issues/19

I basically do not know how to fix this, If you set your host OS to english then set a keymap in the container it works. (not a solution just saying) If anyone has any insights let me know, not many example projects leveraging a custom guac client to go off out there for keyboard definitions.

**Comment by thelamer** [comment]
This has been resolved in the latest image, but it is not universal for everyone reporting here. The available keymaps are here: 
https://github.com/linuxserver/gclient#keyboard-layouts

This is a limitation of Guacamole server as they only have a certain set of keymaps available to pass to the RDP connection: 
https://github.com/apache/guacamole-server/tree/master/src/protocols/rdp/keymaps (RU or Czech is not one of them)

you simply pass `-e KEYBOARD=yourkeymap` to the container for support. 

If your keymap is not supported the only workaround would be to paste in the required characters you need or install an OSK inside of the container to type stuff out. (open a terminal and use apt-get in the main tag pacman in the arch tag)

**Comment by marapavelka** [comment]
On the [https://github.com/apache/guacamole-server/tree/master/src/protocols/rdp/keymaps](https://github.com/apache/guacamole-server/tree/master/src/protocols/rdp/keymaps) is now more languages and Czech is one of them. But even if I set `-e KEYBOARD=cs-cz-qwertz`, it doesn't work

**Comment by alukatsk** [comment]
It is still an issue for Russian language. Also it is not possibel to paste special chars from the clipboard (CTRL-V).

**Comment by marapavelka** [comment]
Thanks for switching to KasmVNC base image, now I can enter Czech characters <3

**Comment by ecser99** [comment]
Latest version **18.03.23: - Rebase to KasmVNC base image** made it possible to simply enter Hungarian special characters. Thanx!

**Comment by fis-common** [comment]
Hello team,

Can please someone advise whether the same issue with the russian keyboard layout is supposed to be fixed in the latest image built on KasmVNC?

Maybe some env variables are required?

**Comment by thespad** [comment]
If it doesn't work ootb, try https://github.com/linuxserver/docker-mods/tree/universal-internationalization

**Comment by fis-common** [comment]
> If it doesn't work ootb, try https://github.com/linuxserver/docker-mods/tree/universal-internationalization

Thank you! It worked - all characters from the local set are available. I really apreciate for your help.
