### ISSUE TITLE
Sending parameters to calibre-server

### ISSUE THREAD

**Issue by yuuzhan** [linuxserver/docker-calibre#30]
I am trying to send the "--url-prefix /calibre" command to calibre server.  Using the CLI_ARGS command sends the command to calibre (which doesnt recognize it).

------------------------------

## Expected Behavior

URL should be localhost:8080/calibre 

## Current Behavior

localhost:8080/ is the url

## Environment
**OS:**  Linux
**CPU architecture:** arm64  
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

```
    calibre:
        image: linuxserver/calibre
        container_name: calibre
        depends_on:
            - vpn
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Toronto
          - CLI_ARGS="--url-prefix /calibre"
        volumes:
          - /storage/dockerConfigs/calibre:/config
          - /storage/Library:/storage/Library
        ports:
          - 8080:8080
          - 8081:8081
        restart: unless-stopped
```

## Docker logs

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 11-moduser: executing...
[cont-init.d] 11-moduser: exited 0.
[cont-init.d] 12-prep_xrdp: executing...
[cont-init.d] 12-prep_xrdp: exited 0.
[cont-init.d] 13-update_app_name: executing...
[cont-init.d] 13-update_app_name: exited 0.
[cont-init.d] 14-configure_openbox: executing...
[cont-init.d] 14-configure_openbox: exited 0.
[cont-init.d] 30-update_webapp_context: executing...
[cont-init.d] 30-update_webapp_context: exited 0.
[cont-init.d] 35-update_guac_creds: executing...
[cont-init.d] 35-update_guac_creds: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-168-generic x86_64 Ubuntu
Current Operating System: Linux 1417ec5662a7 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.3.0-53-generic root=UUID=bbb3effa-4f82-4340-830d-6e97c2f934e6 ro quiet splash vt.handoff=1
Build Date: 14 November 2019  06:20:00PM
xorg-server 2:1.19.6-1ubuntu4.4 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.pid-419.log", Time: Fri May 29 22:21:48 2020
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7fe6b0cff010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000306d4 bx 0x01100800 cx 0x7ffafbbf dx 0xbfebfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpXvInit: depth 24
rdpClientConInit: kill disconnected [0] timeout [0] sec

rdpScreenInit: out
guacd[412]: INFO:       Guacamole proxy daemon (guacd) version 0.9.14 started
guacd[412]: INFO:       Listening on host 127.0.0.1, port 4822
[services.d] done.
rdpmousePreInit: drv 0x55aceef74a50 info 0x55acef0e7be0, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7fe6b10d8c60
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x55aceef692d0 info 0x55acef258800, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7fe6b0ed5530
rdpkeybControl: what 1
rdpkeybDeviceOn:
guacd[412]: INFO:       Guacamole connection closed during handshake
rdpSaveScreen:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpInDeferredUpdateCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
Warning: Cannot convert string "-*-helvetica-bold-r-normal--*-120-*-*-*-*-iso8859-1" to type FontStruct
Warning: Cannot convert string "-*-courier-medium-r-normal--*-120-*-*-*-*-iso8859-1" to type FontStruct
rdpRRGetInfo:
Obt-Message: Xinerama extension is not present on the server
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
rdpRRGetInfo:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
29-May-2020 18:21:51.914 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with JAR file [/usr/share/tomcat8/lib/commons-pool.jar], exists: [false], canRead: [false]
29-May-2020 18:21:51.964 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with JAR file [/usr/share/tomcat8/lib/commons-dbcp.jar], exists: [false], canRead: [false]
29-May-2020 18:21:51.983 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:51.987 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:51.989 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:51.991 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.003 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.006 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.011 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.011 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.018 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.019 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.019 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.026 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
29-May-2020 18:21:52.447 SEVERE [main] org.apache.catalina.startup.Catalina.initDirs Cannot find specified temporary folder at [/var/lib/tomcat8/temp]
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 181, resource id: 0, major code: 140 (Unknown), minor code: 20
29-May-2020 18:21:56.460 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
29-May-2020 18:21:56.467 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
29-May-2020 18:21:56.468 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
29-May-2020 18:21:56.468 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
29-May-2020 18:21:56.469 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.3.0-53-generic
29-May-2020 18:21:56.470 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
29-May-2020 18:21:56.471 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
29-May-2020 18:21:56.472 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.7+10-post-Ubuntu-2ubuntu218.04
29-May-2020 18:21:56.473 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
29-May-2020 18:21:56.473 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
29-May-2020 18:21:56.479 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
29-May-2020 18:21:56.480 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
29-May-2020 18:21:56.487 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
29-May-2020 18:21:56.491 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
29-May-2020 18:21:56.492 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
29-May-2020 18:21:56.493 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
29-May-2020 18:21:56.495 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
29-May-2020 18:21:56.496 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
29-May-2020 18:21:56.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
29-May-2020 18:21:56.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
29-May-2020 18:21:56.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
29-May-2020 18:21:56.509 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
29-May-2020 18:21:56.514 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/var/lib/tomcat8/temp
29-May-2020 18:21:56.515 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
29-May-2020 18:21:56.834 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
29-May-2020 18:21:56.987 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
29-May-2020 18:21:57.173 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 4736 ms
29-May-2020 18:21:57.660 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
29-May-2020 18:21:57.661 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
29-May-2020 18:21:57.775 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/var/lib/tomcat8/webapps/ROOT.war]
DBusExport: Failed to connect to DBUS session bus, with error: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Traceback (most recent call last):
  File "site-packages/calibre/gui2/notify.py", line 159, in get_notifier
  File "site-packages/calibre/gui2/notify.py", line 89, in get_dbus_notifier
  File "site-packages/dbus/_dbus.py", line 211, in __new__
  File "site-packages/dbus/_dbus.py", line 100, in __new__
  File "site-packages/dbus/bus.py", line 122, in __new__
DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
29-May-2020 18:22:02.780 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
18:22:03.580 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
18:22:03.834 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
18:22:04.281 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
18:22:04.298 [localhost-startStop-1] WARN  o.a.g.a.n.NoAuthenticationProvider - The "NoAuth" extension is **DEPRECATED**! This extension will be removed from the Guacamole codebase entirely in a future release. Please consider writing an extension using Guacamole's extension API instead.
18:22:04.390 [localhost-startStop-1] INFO  o.a.g.extension.ExtensionModule - Extension "Disabled Authentication (DEPRECATED)" loaded.
18:22:04.394 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
18:22:04.679 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
29-May-2020 18:22:05.498 WARNING [localhost-startStop-1] com.google.inject.internal.ProxyFactory.<init> Method [public void org.apache.guacamole.rest.user.UserResource.updateObject(java.lang.Object) throws org.apache.guacamole.GuacamoleException] is synthetic and is being intercepted by [org.apache.guacamole.rest.RESTExceptionWrapper@6988a1e6]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
29-May-2020 18:22:05.883 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
29-May-2020 18:22:05.884 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
29-May-2020 18:22:05.884 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
29-May-2020 18:22:05.885 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
29-May-2020 18:22:05.885 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
29-May-2020 18:22:05.886 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
29-May-2020 18:22:05.892 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
29-May-2020 18:22:06.180 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
29-May-2020 18:22:07.189 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
29-May-2020 18:22:07.202 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
29-May-2020 18:22:07.204 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
29-May-2020 18:22:07.212 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
29-May-2020 18:22:07.216 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
29-May-2020 18:22:07.253 INFO [localhost-startStop-1] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
29-May-2020 18:22:07.284 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/var/lib/tomcat8/webapps/ROOT.war] has finished in [9,509] ms
29-May-2020 18:22:07.297 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
29-May-2020 18:22:07.338 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 10151 ms
rdpSaveScreen:
29-May-2020 18:35:21.756 INFO [http-nio-8080-exec-3] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/jquery/2.1.3/dist/jquery.min.js
29-May-2020 18:35:21.757 INFO [http-nio-8080-exec-4] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/lodash/2.4.1/dist/lodash.min.js
29-May-2020 18:35:21.859 INFO [http-nio-8080-exec-6] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-cookies/1.3.16/angular-cookies.min.js
29-May-2020 18:35:21.859 INFO [http-nio-8080-exec-5] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular/1.3.16/angular.min.js
29-May-2020 18:35:21.900 INFO [http-nio-8080-exec-7] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-route/1.3.16/angular-route.min.js
29-May-2020 18:35:21.911 INFO [http-nio-8080-exec-8] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-touch/1.3.16/angular-touch.min.js
29-May-2020 18:35:21.922 INFO [http-nio-8080-exec-9] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/messageformat/1.0.2/messageformat.min.js
29-May-2020 18:35:21.930 INFO [http-nio-8080-exec-10] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-translate/2.8.0/angular-translate.min.js
29-May-2020 18:35:21.975 INFO [http-nio-8080-exec-1] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-translate-interpolation-messageformat/2.8.0/angular-translate-interpolation-messageformat.min.js
29-May-2020 18:35:22.060 INFO [http-nio-8080-exec-2] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/blob-polyfill/1.0.20150320/Blob.js
29-May-2020 18:35:22.060 INFO [http-nio-8080-exec-3] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-translate-loader-static-files/2.8.0/angular-translate-loader-static-files.min.js
29-May-2020 18:35:22.072 INFO [http-nio-8080-exec-4] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/filesaver/1.3.3/FileSaver.min.js
29-May-2020 18:35:22.091 INFO [http-nio-8080-exec-6] org.webjars.servlet.WebjarsServlet.doGet Webjars resource requested: /META-INF/resources/webjars/angular-module-shim/0.0.4/angular-module-shim.js
18:35:22.401 [http-nio-8080-exec-7] INFO  o.a.g.r.auth.AuthenticationService - User "8bc5adab-74da-47fa-95e8-298f1ca837ef" successfully authenticated from 192.168.0.93.
18:35:22.935 [http-nio-8080-exec-4] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/etc/guacamole".
guacd[412]: INFO:       Creating new client for protocol "rdp"
guacd[412]: INFO:       Connection ID is "$cb6ff8dc-de58-4074-9e60-165697b2bed3"
18:35:23.014 [http-nio-8080-exec-4] INFO  o.a.g.tunnel.TunnelRequestService - User "8bc5adab-74da-47fa-95e8-298f1ca837ef" connected to connection "myconfig".
guacd[584]: INFO:       No security mode specified. Defaulting to RDP.
guacd[584]: INFO:       Resize method: none
guacd[584]: INFO:       User "@16c60335-9677-496f-a471-a979f3232b1a" joined connection "$cb6ff8dc-de58-4074-9e60-165697b2bed3" (1 users now present)
guacd[584]: INFO:       Loading keymap "base"
guacd[584]: INFO:       Loading keymap "en-us-qwerty"
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/guacdr-client.so: cannot open shared object file: No such file or directory
guacd[584]: WARNING:    Failed to load guacdr plugin. Drive redirection and printing will not work. Sound MAY not work.
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/guacsnd-client.so: cannot open shared object file: No such file or directory
guacd[584]: WARNING:    Failed to load guacsnd alongside guacdr plugin. Sound will not work. Drive redirection and printing MAY not work.
connected to 127.0.0.1:3389
Unable to find a match for unix timezone: Etc/UTC
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 18
rdpClientConGotConnection: adding only clientCon
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1688 height 806 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 2 shmemptr 0x7fe6a2764000
rdpRRScreenSetSize: width 1688 height 806 mmWidth 447 mmHeight 213
rdpRRGetInfo:
  screen resized to 1688x806
rdpClientConProcessScreenSizeMsg: RRScreenSizeSet ok=[1]
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1688 cy 806
rdpClientConProcessMsgClientInfo:
  got client info bytes 5744
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1688 height 806
rdpLoadLayout: keylayout 0x00000409 variant  display 1
fuse: device not found, try 'modprobe fuse' first
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
fuse: device not found, try 'modprobe fuse' first
rdpInDeferredUpdateCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:
rdpSaveScreen:

```

**Comment by aptalca** [comment]
That arg only affects the calibre webserver that is served on port 8081
