### ISSUE TITLE
After updating docker on 7 Mar 2022, can't login any more

### ISSUE THREAD

**Issue by europacafe** [linuxserver/docker-calibre#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Just upgrade the Calibre docker image file in Unraid docker, it can display login screen, entering login/password can't login any more with message:
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login failed for display 0

------------------------------

## Expected Behavior
Should be able to login as usual (no problem logging on before the upgrade)
## Current Behavior
Can't login after entering the correct login and password. The error message is as follows:
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login failed for display 0

## Steps to Reproduce

1. from Unraid docker page, select webui, then login screen displays
2. enter user and password
3. it displays the message as mentioned above

## Environment
**OS: Unraid 6.9.2
**CPU architecture:** x86_64/arm64
**How docker service was installed:**
from Unraid docker management.

## Command used to create docker container (run/create/compose/screenshot)
press update button on Unraid docker management screen

## Docker logs
[Calibre_log.txt](https://github.com/linuxserver/docker-calibre/files/8195441/Calibre_log.txt)

**Comment by europacafe** [comment]
[log](https://www.toptal.com/developers/hastebin/evayoxobaf.yaml)
I'm not sure where in unraid I can see the docker run command.

**Comment by newb23** [comment]
Not sure if it helps you @europacafe, but I had the same bnehavior. Tried going all the way back to v5.36.0 with no luck, until I removed my mapping for /tmp, leaving the default. 

I would prefer to be able to move /tmp off into my appdata directory, but, I also would rather it work, more than anything. Ha!

**Comment by europacafe** [comment]
My calibre docker setup does not have the option to specify /tmp location. Where is its default location?

**Comment by newb23** [comment]
> Where is its default location?

Default is internal of the container itself. Sorry it wasn't more help!

**Comment by europacafe** [comment]
I saw the container tmp folder. Not sure if I delete the tmp directory, would my Calibre container be able to start?

**Comment by europacafe** [comment]
I scrapped the container, re-download the latest image, still have the same symptom, i.e, it won't display Calibre GUI after entering login and password. Same log message

**Comment by Pheoxy** [comment]
I am having the same issue with setting environment variable "PASSWORD".

![image](https://user-images.githubusercontent.com/6779172/163728097-f35a7100-ed22-421e-99e5-d20653649291.png)

**Comment by aptalca** [comment]
Still not a single person posted their compose yaml or docker run arguments (or a visible log).
With this docker run, it works just fine: `docker run -d --rm --name test -p 8080:8080 -e PASSWORD=test ghcr.io/linuxserver/calibre` I can log in with `abc:test`

Closing

**Comment by europacafe** [comment]
I found the cause of the problem. After removing the PASSWORD environment in the docker, it works properly. I'm not sure why adding PASSWORD parameter to the docker causes such problem, even though I always entered the right password at the login page.

**Comment by delize** [comment]
@aptalca here is a docker inspect/yaml and a log output of when attempting to login:

```
$ cat docker-compose.yml #(specifically calibre, no other sections)
calibre:
        image: ghcr.io/linuxserver/calibre
        container_name: calibre
        networks:
            - dl_auto
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=America/Chicago
            - PASSWORD=${CALIBREPASS} #optional
            - CLI_ARGS= #optional
            - SUBFOLDER=/calibre/
        volumes:
            - /mnt/cache/docker/calibre:/config:slave
            - '/mnt/mergerfs/ebooks:/pool/books:slave'

        #ports:
            # - 8080:8080
            # - 8081:8081
        restart: unless-stopped
        #depends_on:
        #    - mergerfs-calibre

$ docker inspect calibre
[
    {
        "Id": "7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81",
        "Created": "2022-04-18T06:00:24.762641372Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2128729,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-04-23T14:56:52.148170992Z",
            "FinishedAt": "2022-04-23T14:56:51.594859522Z"
        },
        "Image": "sha256:558c3773ff879646a5e7a9c7d63850f3cc026d94aa1af686cdfe0fa3815a18e3",
        "ResolvConfPath": "/var/lib/docker/containers/7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81/hostname",
        "HostsPath": "/var/lib/docker/containers/7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81/hosts",
        "LogPath": "/var/lib/docker/containers/7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81/7ec68c23a0e76dcc4e256f7089d6f3e4d36f7f5834fd1ac35f9a57b2372d9c81-json.log",
        "Name": "/calibre",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/cache/docker/calibre:/config:slave",
                "/mnt/mergerfs/ebooks:/pool/books:slave"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "dl_auto",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/884ebd2618a4c2dd42b64da287336525a0478bec5e722e8a2887a2b1893f3710-init/diff:/var/lib/docker/overlay2/3a67e8d57d502a780e19eeff395966eceaeab45db516ceac6ab30dce07f82113/diff:/var/lib/docker/overlay2/43c6dfc92e5d48450e24d2562946f7958e305248cb7327fdacec8bca61e7bce2/diff:/var/lib/docker/overlay2/72fcbdcc168c733e70b8e682c3fed4afe96106ac2b13ea4df3e3165bb023bb7f/diff:/var/lib/docker/overlay2/ed87faee6694b7dc6d18be65edb0e873d995c15bb34aafe7bb0fc632a5c6406d/diff:/var/lib/docker/overlay2/ee7db0fee9976011090394e054ec7b3abb2b01f1cd925fab6faed61cf485ecc8/diff:/var/lib/docker/overlay2/05612d9b3a4e0336f7dcf702733e5fada0ab2ef40c0d04bf95bb41348dfc0ef3/diff:/var/lib/docker/overlay2/98063afbcc8ac315cc03bff195c63fbb55a4033bebf834eaeb38a1aaa3a0285b/diff:/var/lib/docker/overlay2/37e93864655133c00d7c50eb3d97bf8b9c488b8be3ed1059f54fb00a7ffd0832/diff:/var/lib/docker/overlay2/ae15afc74f30976e8f3f82ab18d980200e435312a75a2c7aab41a236fbb5216f/diff:/var/lib/docker/overlay2/22de11b877469fd747149866f6a0f03873b6509a5f6c4c92c561c1171f573b74/diff:/var/lib/docker/overlay2/4fc437ac3d17512087a99134efe3089adf40d915939556ade2aef7da9d5e1217/diff:/var/lib/docker/overlay2/1682e4a052f46d2beaf4c6fabd0beaf55f8817b00fce4b631762560c7bc8b677/diff:/var/lib/docker/overlay2/1cd4b174e9798be88b452688d7b47e12ac80abfabd5206831b68d5028259345d/diff:/var/lib/docker/overlay2/f12587dfccace74c9d8ca3411bd937a44d4eb6baaf7cd1fb0cf764a99e971f72/diff:/var/lib/docker/overlay2/a0f50ec6518ed72a6f2f23d8f0c7c6986912b727b0b9465c6b62dd798dceba42/diff:/var/lib/docker/overlay2/321ff847c83c6b0ea43e87cc21d8abb3a5929b1cc1b62bb9c6638d2f44887932/diff:/var/lib/docker/overlay2/b72168ff6a343c4c6f12f53a4680d6d5d38c51ec96c4c1237795fb3da33a5084/diff",
                "MergedDir": "/var/lib/docker/overlay2/884ebd2618a4c2dd42b64da287336525a0478bec5e722e8a2887a2b1893f3710/merged",
                "UpperDir": "/var/lib/docker/overlay2/884ebd2618a4c2dd42b64da287336525a0478bec5e722e8a2887a2b1893f3710/diff",
                "WorkDir": "/var/lib/docker/overlay2/884ebd2618a4c2dd42b64da287336525a0478bec5e722e8a2887a2b1893f3710/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/cache/docker/calibre",
                "Destination": "/config",
                "Mode": "slave",
                "RW": true,
                "Propagation": "slave"
            },
            {
                "Type": "bind",
                "Source": "/mnt/mergerfs/ebooks",
                "Destination": "/pool/books",
                "Mode": "slave",
                "RW": true,
                "Propagation": "slave"
            }
        ],
        "Config": {
            "Hostname": "7ec68c23a0e7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {},
                "3389/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=1000",
                "PGID=1000",
                "TZ=America/Chicago",
                "PASSWORD=OMIT!",
                "CLI_ARGS=",
                "SUBFOLDER=/calibre/",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/config",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
                "CUSTOM_PORT=8080",
                "GUIAUTOSTART=true"
            ],
            "Cmd": null,
            "Image": "ghcr.io/linuxserver/calibre",
            "Volumes": {
                "/config": {},
                "/pool/books": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- v5.40.0-ls157 Build-date:- 2022-04-16T22:36:16-05:00",
                "com.docker.compose.config-hash": "2318ae4426b565758ce3817e0d513ac401dc6e22502c28789e687ed439a20b2b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "dl_auto",
                "com.docker.compose.project.config_files": "/home/andrew/dl_auto/dl_auto.yml",
                "com.docker.compose.project.environment_file": "/home/andrew/dl_auto/.env",
                "com.docker.compose.project.working_dir": "/home/andrew/dl_auto",
                "com.docker.compose.service": "calibre",
                "com.docker.compose.version": "1.25.0",
                "maintainer": "aptalca",
                "org.opencontainers.image.authors": "linuxserver.io",
                "org.opencontainers.image.created": "2022-04-16T22:36:16-05:00",
                "org.opencontainers.image.description": "[Calibre](https://calibre-ebook.com/) is a powerful and easy to use e-book manager. Users say it’s outstanding and a must-have. It’ll allow you to do nearly everything and it takes things a step beyond normal e-book software. It’s also completely free and open source and great for both casual users and computer experts.",
                "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-calibre",
                "org.opencontainers.image.licenses": "GPL-3.0-only",
                "org.opencontainers.image.ref.name": "9608db7a47613d0313b1bc22244ebc669607cb38",
                "org.opencontainers.image.revision": "9608db7a47613d0313b1bc22244ebc669607cb38",
                "org.opencontainers.image.source": "https://github.com/linuxserver/docker-calibre",
                "org.opencontainers.image.title": "Calibre",
                "org.opencontainers.image.url": "https://github.com/linuxserver/docker-calibre/packages",
                "org.opencontainers.image.vendor": "linuxserver.io",
                "org.opencontainers.image.version": "v5.40.0-ls157"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ecba9cc645ab8df26edf786a88dd5ae9ea66b3c16ac8419084d06d875f301069",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": null,
                "3389/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/ecba9cc645ab",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "dl_auto": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "calibre",
                        "7ec68c23a0e7"
                    ],
                    "NetworkID": "7760cb5053153c42f4b15176cc81db171dc8f27bb2399996f6a1815b6af14f2f",
                    "EndpointID": "0391f8c43c7257d9968bac552e39d9347c7a7564c0d63e7850137e225d7402c3",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.15",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:13:00:0f",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

```
$ docker logs -f calibre > ~/calibre.log
Can't load /config/.rnd into RNG
140288205455808:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/config/.rnd
Generating a RSA private key
......................................................................................+++++
........................................................................................................................................................................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
guacd[457]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[457]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[457]: INFO:	Guacamole connection closed during handshake
guacd[457]: INFO:	Guacamole connection closed during handshake
guacd[457]: INFO:	Creating new client for protocol "rdp"
guacd[457]: INFO:	Connection ID is "$bcf17918-aac5-4b79-8510-ce57c6a826e9"
guacd[508]: INFO:	Security mode: Negotiate (ANY)
guacd[508]: INFO:	Resize method: none
guacd[508]: INFO:	User "@9f78e2a4-2405-4a52-b54b-4cc5c314f2bc" joined connection "$bcf17918-aac5-4b79-8510-ce57c6a826e9" (1 users now present)
guacd[508]: INFO:	Loading keymap "base"
guacd[508]: INFO:	Loading keymap "en-us-qwerty"
guacd[508]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[508]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[508]: INFO:	Connected to RDPDR 1.12 as client 0x8bf7accd
guacd[508]: INFO:	RDPDR user logged on
[2022-04-18 01:00:42] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
guacd[508]: INFO:	User "@9f78e2a4-2405-4a52-b54b-4cc5c314f2bc" disconnected (0 users remain)
guacd[508]: INFO:	Last user of connection "$bcf17918-aac5-4b79-8510-ce57c6a826e9" disconnected
guacd[508]: INFO:	Internal RDP client disconnected
guacd[457]: INFO:	Connection "$bcf17918-aac5-4b79-8510-ce57c6a826e9" removed.
usermod: no changes
guacd[447]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[447]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[447]: INFO:	Guacamole connection closed during handshake
guacd[447]: INFO:	Guacamole connection closed during handshake
guacd[447]: INFO:	Guacamole connection closed during handshake
guacd[447]: INFO:	Creating new client for protocol "rdp"
guacd[447]: INFO:	Connection ID is "$cf8384d5-b0a9-4bc6-97cd-8e2886636325"
guacd[502]: INFO:	Security mode: Negotiate (ANY)
guacd[502]: INFO:	Resize method: none
guacd[502]: INFO:	User "@2d48923d-d029-421f-8a04-47b7b7d949dd" joined connection "$cf8384d5-b0a9-4bc6-97cd-8e2886636325" (1 users now present)
guacd[502]: INFO:	Loading keymap "base"
guacd[502]: INFO:	Loading keymap "en-us-qwerty"
guacd[502]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[502]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[502]: INFO:	Connected to RDPDR 1.12 as client 0x3a107b89
guacd[502]: INFO:	RDPDR user logged on
[2022-04-18 02:37:35] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
guacd[502]: INFO:	User "@2d48923d-d029-421f-8a04-47b7b7d949dd" disconnected (0 users remain)
guacd[502]: INFO:	Last user of connection "$cf8384d5-b0a9-4bc6-97cd-8e2886636325" disconnected
guacd[502]: INFO:	Internal RDP client disconnected
guacd[447]: INFO:	Connection "$cf8384d5-b0a9-4bc6-97cd-8e2886636325" removed.
guacd[447]: INFO:	Creating new client for protocol "rdp"
guacd[447]: INFO:	Connection ID is "$0858edb8-6956-4a7d-8077-bf3a864e6fb6"
guacd[654]: INFO:	Security mode: Negotiate (ANY)
guacd[654]: INFO:	Resize method: none
guacd[654]: INFO:	User "@0a84d7f5-1e6b-4adc-821e-94aef33a028d" joined connection "$0858edb8-6956-4a7d-8077-bf3a864e6fb6" (1 users now present)
guacd[654]: INFO:	Loading keymap "base"
guacd[654]: INFO:	Loading keymap "en-us-qwerty"
guacd[654]: INFO:	User "@0a84d7f5-1e6b-4adc-821e-94aef33a028d" disconnected (0 users remain)
guacd[654]: INFO:	Last user of connection "$0858edb8-6956-4a7d-8077-bf3a864e6fb6" disconnected
[2022-04-23 09:52:22] [Connection 2]  Closing connection with error:  1000
guacd[654]: INFO:	Internal RDP client disconnected
guacd[447]: INFO:	Connection "$0858edb8-6956-4a7d-8077-bf3a864e6fb6" removed.
guacd[447]: INFO:	Creating new client for protocol "rdp"
guacd[447]: INFO:	Connection ID is "$2c6d16e5-6be8-4108-b345-42ff15c16be0"
guacd[689]: INFO:	Security mode: Negotiate (ANY)
guacd[689]: INFO:	Resize method: none
guacd[689]: INFO:	User "@f253bd0f-84f9-469e-9fd1-8cc3ec6bec15" joined connection "$2c6d16e5-6be8-4108-b345-42ff15c16be0" (1 users now present)
guacd[689]: INFO:	Loading keymap "base"
guacd[689]: INFO:	Loading keymap "en-us-qwerty"
usermod: no changes
guacd[453]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[453]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[453]: INFO:	Creating new client for protocol "rdp"
guacd[453]: INFO:	Connection ID is "$0efe7d60-706c-4a21-a2b7-30a9e191ac33"
guacd[478]: INFO:	Security mode: Negotiate (ANY)
guacd[478]: INFO:	Resize method: none
guacd[478]: INFO:	User "@ca154beb-1578-4ca1-9888-2b1aa7eee914" joined connection "$0efe7d60-706c-4a21-a2b7-30a9e191ac33" (1 users now present)
guacd[478]: INFO:	Loading keymap "base"
guacd[478]: INFO:	Loading keymap "en-us-qwerty"
guacd[453]: INFO:	Guacamole connection closed during handshake
guacd[453]: INFO:	Creating new client for protocol "rdp"
guacd[453]: INFO:	Connection ID is "$e567335f-0d7f-4303-bbbc-79326d85bf1c"
guacd[517]: INFO:	Security mode: Negotiate (ANY)
guacd[517]: INFO:	Resize method: none
guacd[517]: INFO:	User "@884b78ad-b131-4597-b71a-ea27ee620333" joined connection "$e567335f-0d7f-4303-bbbc-79326d85bf1c" (1 users now present)
guacd[517]: INFO:	Loading keymap "base"
guacd[517]: INFO:	Loading keymap "en-us-qwerty"
guacd[517]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[517]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[517]: INFO:	Connected to RDPDR 1.12 as client 0x3014cbf4
guacd[517]: INFO:	RDPDR user logged on
[2022-04-23 09:53:30] [Connection 2]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
guacd[517]: ERROR:	User is not responding.
guacd[517]: INFO:	User "@884b78ad-b131-4597-b71a-ea27ee620333" disconnected (0 users remain)
guacd[517]: INFO:	Last user of connection "$e567335f-0d7f-4303-bbbc-79326d85bf1c" disconnected
guacd[517]: INFO:	Internal RDP client disconnected
guacd[453]: INFO:	Connection "$e567335f-0d7f-4303-bbbc-79326d85bf1c" removed.
usermod: no changes
guacd[451]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[451]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[451]: INFO:	Guacamole connection closed during handshake
guacd[451]: INFO:	Creating new client for protocol "rdp"
guacd[451]: INFO:	Connection ID is "$92f59efa-1957-4e7c-ad90-25664866d627"
guacd[497]: INFO:	Security mode: Negotiate (ANY)
guacd[497]: INFO:	Resize method: none
guacd[497]: INFO:	User "@f373b1fc-9377-4daa-bb06-84d55fbb77a7" joined connection "$92f59efa-1957-4e7c-ad90-25664866d627" (1 users now present)
guacd[497]: INFO:	Loading keymap "base"
guacd[497]: INFO:	Loading keymap "en-us-qwerty"
guacd[497]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[497]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[497]: INFO:	Connected to RDPDR 1.12 as client 0x5fa22a34
guacd[497]: INFO:	RDPDR user logged on
[2022-04-23 09:55:53] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
guacd[497]: ERROR:	User is not responding.
guacd[497]: INFO:	User "@f373b1fc-9377-4daa-bb06-84d55fbb77a7" disconnected (0 users remain)
guacd[497]: INFO:	Last user of connection "$92f59efa-1957-4e7c-ad90-25664866d627" disconnected
guacd[497]: INFO:	Internal RDP client disconnected
guacd[451]: INFO:	Connection "$92f59efa-1957-4e7c-ad90-25664866d627" removed.
usermod: no changes
guacd[456]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[456]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[456]: INFO:	Guacamole connection closed during handshake
guacd[456]: INFO:	Creating new client for protocol "rdp"
guacd[456]: INFO:	Connection ID is "$21322182-c663-4f2c-aadd-ad218435437c"
guacd[494]: INFO:	Security mode: Negotiate (ANY)
guacd[494]: INFO:	Resize method: none
guacd[494]: INFO:	User "@4158d79c-877a-45cf-ba6c-df5a00f23601" joined connection "$21322182-c663-4f2c-aadd-ad218435437c" (1 users now present)
guacd[494]: INFO:	Loading keymap "base"
guacd[494]: INFO:	Loading keymap "en-us-qwerty"
guacd[494]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[494]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[494]: INFO:	Connected to RDPDR 1.12 as client 0x40b90c9e
guacd[494]: INFO:	RDPDR user logged on
[2022-04-23 09:57:03] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
guacd[494]: ERROR:	User is not responding.
guacd[494]: INFO:	User "@4158d79c-877a-45cf-ba6c-df5a00f23601" disconnected (0 users remain)
guacd[494]: INFO:	Last user of connection "$21322182-c663-4f2c-aadd-ad218435437c" disconnected
guacd[494]: INFO:	Internal RDP client disconnected
guacd[456]: INFO:	Connection "$21322182-c663-4f2c-aadd-ad218435437c" removed.
guacd[456]: INFO:	Creating new client for protocol "rdp"
guacd[456]: INFO:	Connection ID is "$18b3bea8-4622-4bf5-884d-c14c23037063"
guacd[635]: INFO:	Security mode: Negotiate (ANY)
guacd[635]: INFO:	Resize method: none
guacd[635]: INFO:	User "@afdac82a-fbb0-4a0d-873f-954bcb78680b" joined connection "$18b3bea8-4622-4bf5-884d-c14c23037063" (1 users now present)
guacd[635]: INFO:	Loading keymap "base"
guacd[635]: INFO:	Loading keymap "en-us-qwerty"
```
I receive the same message as @Pheoxy in the photo that was posted.
