### ISSUE TITLE
Missing icu 71 required by calibre but 70 required by freerdp and mesa

### ISSUE THREAD

**Issue by prahal** [linuxserver/docker-calibre#81]
## Expected Behavior
calibre starts

## Current Behavior
calibre fails to start
running an xterm and running claibre from there shows errors about libicui18n.so.71 and libicuuc.so.71 missing
```
File "/usr/lib/calibre/calibre/startup.py" line 124 in initialize_calibre
  from calibre.utils.icu import title_case, lower as icu_lower, upper as icu_upper
File "/usr/lib/calibre/calibre/utils/icu.py", line 12, in <module>
 from calibre_extensions import icu as _icu
ImportError: libicuuc.so.71: cannot open shared object file: No such file or directory
```

## Steps to Reproduce
1. Connect to rdp 3389
2. right click on the background and click xterm
3. enter calibre then press enter

## Environment
**OS:** arch
**CPU architecture:** arm64
**How docker service was installed:**
from the official docker repo with a few local docker-mods to read fril remotely and manage trashbin
`DOCKER_MODS=abws/mods:calibre-readers|abws/mods:calibre-pyqtwebengine|abws/mods:calibre-pycryptodome|abws/mods:calibre-filemanager`

## Command used to create docker container (run/create/compose/screenshot)
portainer  stack 
```
---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:arm64v8-arch
    container_name: calibre
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/Paris
      - DOCKER_MODS=abws/mods:calibre-readers|abws/mods:calibre-pyqtwebengine|abws/mods:calibre-pycryptodome|abws/mods:calibre-filemanager
      - TMPDIR=$HOME/tmp
    volumes:
      - /srv/dev-disk-by-label-secure/appdata/docker/calibre:/config
      - /srv/dev-disk-by-label-store/media/calibre:/Calibre_Library
    ports:
      - 3389:3389
      - 8080:8080
      - 8081:8081
      - 9090:9090
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
```
Then I created a mod to upgrade icu and freerdp but now this is mesa swrast that fails because now that icu 71 is installed swrast complains that icu 70 is missing.
`pacman -S community/freerdp`
`libGL error: MESA-LOADER: failed to open swrast: libicuuc.so.70: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)`

## Docker logs
```
phn@helios64:~$ sudo docker logs calibre
[mod-init] Curl/JQ was not found on this system for Docker mods installing
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 alarm downloading...
 aur downloading...
resolving dependencies...
looking for conflicting packages...

Packages (3) oniguruma-6.9.7.1-2  curl-7.82.0-2  jq-1.6-4

Total Download Size:   1.43 MiB
Total Installed Size:  3.36 MiB
Net Upgrade Size:      1.55 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 curl-7.82.0-2-aarch64 downloading...
 jq-1.6-4-aarch64 downloading...
 oniguruma-6.9.7.1-2-aarch64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading curl...
installing oniguruma...
installing jq...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying abws/mods:calibre-readers files to container
[mod-init] Applying abws/mods:calibre-pyqtwebengine files to container
[mod-init] Applying abws/mods:calibre-pycryptodome files to container
[mod-init] Applying abws/mods:calibre-filemanager files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 13-keygen: executing... 

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to rsakeys.ini

Generating a RSA private key
..............................+++++
.....................................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
[cont-init.d] 13-keygen: exited 0.
[cont-init.d] 30-config: executing... 
chsh: Shell not changed.
Changing shell for abc.
[cont-init.d] 30-config: exited 1.
[cont-init.d] 50-config: executing... 
**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****
chown: cannot access '/opt/calibre': No such file or directory
[cont-init.d] 50-config: exited 1.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 55-autostart-config: executing... 
[cont-init.d] 55-autostart-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 98-filemanager: executing... 
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 alarm downloading...
 aur downloading...
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: usbmuxd will be installed before its libimobiledevice dependency

Packages (39) bubblewrap-0.6.1-1  exempi-2.6.1-1  exiv2-0.27.5-1  fuse3-3.10.5-1  gcr-3.41.0-2  gnome-autoar-0.4.3-2  gnome-desktop-1:42.0-1  gnome-desktop-common-1:42.0-1  gupnp-dlna-0.12.0-1  gvfs-1.50.1-1  jansson-2.14-1  libcddb-1.3.2-6  libcdio-2.1.0-2  libcdio-paranoia-10.2+2.0.1-2  libcue-2.2.1-2  libexif-0.6.24-1  libgexiv2-0.14.0-3  libgrss-0.7.0+16+g971c421-3  libgsf-1.14.49-1  libgxps-0.3.2-1  libhandy-1.6.2-1  libimobiledevice-1.3.0-5  libiptcdata-1.0.4-5  libnautilus-extension-42.1.1-1  libnm-1.36.4-1  libosinfo-1.10.0-1  libplist-2.2.0-5  libportal-0.6-1  libportal-gtk3-0.6-1  libusbmuxd-2.0.2-1  osinfo-db-20220214-1  poppler-22.03.0-1  poppler-glib-22.03.0-1  psmisc-23.4-1  totem-pl-parser-3.26.6-1  tracker3-miners-3.3.0-2  upower-0.99.17-1  usbmuxd-1.1.1-1  nautilus-42.1.1-1

Total Download Size:   13.35 MiB
Total Installed Size:  87.47 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 nautilus-42.1.1-1-aarch64 downloading...
 exiv2-0.27.5-1-aarch64 downloading...
 poppler-22.03.0-1-aarch64 downloading...
 libnm-1.36.4-1-aarch64 downloading...
 gvfs-1.50.1-1-aarch64 downloading...
 gcr-3.41.0-2-aarch64 downloading...
 tracker3-miners-3.3.0-2-aarch64 downloading...
 exempi-2.6.1-1-aarch64 downloading...
 gnome-desktop-common-1:42.0-1-aarch64 downloading...
 libexif-0.6.24-1-aarch64 downloading...
 libhandy-1.6.2-1-aarch64 downloading...
 libimobiledevice-1.3.0-5-aarch64 downloading...
 libgsf-1.14.49-1-aarch64 downloading...
 libosinfo-1.10.0-1-aarch64 downloading...
 poppler-glib-22.03.0-1-aarch64 downloading...
 libcdio-2.1.0-2-aarch64 downloading...
 osinfo-db-20220214-1-any downloading...
 psmisc-23.4-1-aarch64 downloading...
 upower-0.99.17-1-aarch64 downloading...
 totem-pl-parser-3.26.6-1-aarch64 downloading...
 libgexiv2-0.14.0-3-aarch64 downloading...
 fuse3-3.10.5-1-aarch64 downloading...
 libplist-2.2.0-5-aarch64 downloading...
 gnome-desktop-1:42.0-1-aarch64 downloading...
 libgxps-0.3.2-1-aarch64 downloading...
 libgrss-0.7.0+16+g971c421-3-aarch64 downloading...
 gupnp-dlna-0.12.0-1-aarch64 downloading...
 libportal-0.6-1-aarch64 downloading...
 gnome-autoar-0.4.3-2-aarch64 downloading...
 libiptcdata-1.0.4-5-aarch64 downloading...
 libcdio-paranoia-10.2+2.0.1-2-aarch64 downloading...
 libnautilus-extension-42.1.1-1-aarch64 downloading...
 jansson-2.14-1-aarch64 downloading...
 libcddb-1.3.2-6-aarch64 downloading...
 usbmuxd-1.1.1-1-aarch64 downloading...
 bubblewrap-0.6.1-1-aarch64 downloading...
 libusbmuxd-2.0.2-1-aarch64 downloading...
 libcue-2.2.1-2-aarch64 downloading...
 libportal-gtk3-0.6-1-aarch64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing exiv2...
installing libgexiv2...
installing bubblewrap...
installing gnome-desktop-common...
installing gnome-desktop...
installing fuse3...
installing libcddb...
installing libcdio...
installing libcdio-paranoia...
installing gcr...
Created symlink /etc/systemd/user/sockets.target.wants/gcr-ssh-agent.socket → /usr/lib/systemd/user/gcr-ssh-agent.socket.
>>> gcr contains /etc/security/limits.d/10-gcr.conf which sets the memlock limit
    in order to allow GCR to lock private keys in memory. If you have configured
    this limit differently before, please review your configuration.
installing psmisc...
installing gvfs...
Optional dependencies for gvfs
    gvfs-afc: AFC (mobile devices) support
    gvfs-smb: SMB/CIFS (Windows client) support
    gvfs-gphoto2: gphoto2 (PTP camera/MTP media player) support
    gvfs-mtp: MTP device support
    gvfs-goa: gnome-online-accounts (e.g. OwnCloud) support
    gvfs-nfs: NFS support
    gvfs-google: Google Drive support
    gtk3: Recent files support [installed]
installing exempi...
installing libexif...
installing libcue...
installing libgrss...
installing libgsf...
installing libgxps...
installing libiptcdata...
installing osinfo-db...
installing libosinfo...
installing poppler...
Optional dependencies for poppler
    poppler-data: highly recommended encoding data to display PDF documents with certain encodings and characters
installing poppler-glib...
installing totem-pl-parser...
installing gupnp-dlna...
installing libplist...
installing libusbmuxd...
installing usbmuxd...
installing libimobiledevice...
installing upower...
installing jansson...
installing libnm...
installing tracker3-miners...
installing gnome-autoar...
installing libhandy...
installing libportal...
installing libportal-gtk3...
installing libnautilus-extension...
installing nautilus...
Optional dependencies for nautilus
    nautilus-sendto: Send files via mail extension
:: Running post-transaction hooks...
( 1/13) Creating system user accounts...
Creating group 'usbmux' with GID 140.
Creating user 'usbmux' (usbmux user) with UID 140 and GID 140.
( 2/13) Reloading system manager configuration...
  Skipped: Current root is not booted.
( 3/13) Creating temporary files...
( 4/13) Reloading device manager configuration...
  Skipped: Device manager is not running.
( 5/13) Arming ConditionNeedsUpdate...
( 6/13) Updating the MIME type database...
( 7/13) Reloading system bus configuration...
  Skipped: Current root is not booted.
( 8/13) Updating GIO module cache...
( 9/13) Compiling GSettings XML schema files...
(10/13) Updating icon theme caches...
(11/13) Reloading GVFS config...
(12/13) Updating the info directory file...
(13/13) Updating the desktop file MIME type cache...
[cont-init.d] 98-filemanager: exited 0.
[cont-init.d] 98-pycryptodome: executing... 
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 alarm downloading...
 aur downloading...
resolving dependencies...
looking for conflicting packages...

Packages (1) python-pycryptodome-3.14.1-1

Total Download Size:   0.93 MiB
Total Installed Size:  3.35 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-pycryptodome-3.14.1-1-aarch64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing python-pycryptodome...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[cont-init.d] 98-pycryptodome: exited 0.
[cont-init.d] 98-pyqtwebengine: executing... 
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 alarm downloading...
 aur downloading...
resolving dependencies...
looking for conflicting packages...

Packages (1) python-pyqt5-webengine-5.15.5-4

Total Download Size:   0.10 MiB
Total Installed Size:  0.63 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-pyqt5-webengine-5.15.5-4-aarch64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing python-pyqt5-webengine...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[cont-init.d] 98-pyqtwebengine: exited 0.
[cont-init.d] 98-readers: executing... 
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 alarm downloading...
 aur downloading...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing icu (71.1-1) breaks dependency 'libicuuc.so=70-64' required by freerdp
[cont-init.d] 98-readers: exited 1.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
guacd[911]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[911]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
guacd[911]: INFO:	Guacamole connection closed during handshake
Starting guacamole-lite websocket server
listening on *:8080
guacd[911]: INFO:	Guacamole connection closed during handshake
[guac-init] Auto start set, starting application
[2022-04-24 18:28:26] [Connection 1]  Client connection open
[2022-04-24 18:28:26] [Connection 1]  Opening guacd connection
[2022-04-24 18:28:26] [Connection 1]  guacd connection open
[2022-04-24 18:28:26] [Connection 1]  Selecting connection type: rdp
[2022-04-24 18:28:26] [Connection 1]  Sending opCode: 6.select,3.rdp;
guacd[911]: INFO:	Creating new client for protocol "rdp"
guacd[911]: INFO:	Connection ID is "$42ccbcd0-599c-4a88-8bab-2a9677be0e07"
[2022-04-24 18:28:28] [Connection 1]  Sending opCode: 4.size,4.1024,3.768,2.96;
[2022-04-24 18:28:28] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
[2022-04-24 18:28:28] [Connection 1]  Sending opCode: 5.video;
[2022-04-24 18:28:28] [Connection 1]  Sending opCode: 5.image;
[2022-04-24 18:28:28] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2022-04-24 18:28:28] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1024,3.768,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
guacd[993]: INFO:	Security mode: Negotiate (ANY)
guacd[993]: INFO:	Resize method: none
guacd[993]: INFO:	User "@71fdc520-925f-4167-91a4-280bf4474857" joined connection "$42ccbcd0-599c-4a88-8bab-2a9677be0e07" (1 users now present)
5.ready,37.$42ccbcd0-599c-4a88-8bab-2a9677be0e07;
guacd[993]: INFO:	Loading keymap "base"
guacd[993]: INFO:	Loading keymap "en-us-qwerty"
5.audio,1.1,31.audio/L16;rate=44100,channels=2;4.size,1.0,4.1024,3.768;4.size,2.-1,2.11,2.16;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,232.iVBORw0KGgoAAAANSUhEUgAAAAsAAAAQCAYAAADAvYV+AAAABmJLR0QA/wD/AP+gvaeTAAAAYklEQVQokY2RQQ4AIQgDW+L/v9y9qCEsIJ4QZggoJAnDYwAwFQwASI4EO8FEMH95CRYTnfCDOyGFK6GEM6GFo7AqKI4sSSsCJH1X+roFkKdjueABX/On77lz2uGtr6pj9okfTeJQAYVaxnMAAAAASUVORK5CYII=;3.end,1.3;6.cursor,1.0,1.0,2.-1,1.0,1.0,2.11,2.16;
4.sync,9.958413289;
4.sync,9.958413540;
4.size,2.-1,2.32,2.32;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,240.iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAAaElEQVRYhe2WSwrAIAwFfaX3v3K6ceF38VRaCjO7SEwGBWNKAPAxcpIjIqrNkkZrTs3bSc4NKqEmdsv5AmUTSUtNj5CPPtorcLkO+SCAAAIIILCMNYxm7365/vY47mKX3XHcfUgA4Hc8/F4zGEf7ahwAAAAASUVORK5CYII=;3.end,1.3;6.cursor,2.15,2.16,2.-1,1.0,1.0,2.32,2.32;
4.sync,9.958413764;
4.size,2.-1,2.32,2.32;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,276.iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAAgklEQVRYhe2UOxLAIAhEd5nc/8qbBjOOMbECGl6lWOzDHyQJhRgAVEoYAJAsk7AxqJKweVIhYWshW+IlkC2xFciU+BTIkvgVyJC4vhbWTEkiyVABSZgzIgJXniPwcI7OUy/hCI8O27Lr0mvyYewrKOv8RNYuHP+BUuRUezRN0zRNKDeQH1722aSHGAAAAABJRU5ErkJggg==;3.end,1.3;6.cursor,1.0,1.0,2.-1,1.0,1.0,2.32,2.32;
4.sync,9.958413913;
4.sync,9.958414163;
4.sync,9.958414414;
4.sync,9.958414664;
4.sync,9.958414915;
4.sync,9.958415165;
4.sync,9.958415416;
4.sync,9.958415666;
4.sync,9.958415916;
sh: line 1: xauth: command not found
4.sync,9.958416167;

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux 1df24a4b4215 5.15.25-rockchip64 #22.02.1 SMP PREEMPT Sun Feb 27 09:05:47 UTC 2022 aarch64
Kernel command line: root=UUID=a79a14c0-3cf4-4fb9-a6c6-838571351371 rootwait rootfstype=ext4 console=ttyS2,1500000 console=tty1 consoleblank=0 loglevel=7 ubootpart=21825e31-01 usb-storage.quirks=0x2537:0x1066:u,0x2537:0x1068:u,0x0bc2:0x231a:u zswap.enabled=0  cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Sun Apr 24 16:28:34 2022
4.sync,9.958416417;
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
4.sync,9.958416667;
4.sync,9.958416918;
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0xffff8bc8b010
rdpSimdInit: assigning yuv functions
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
4.sync,9.958417168;
4.sync,9.958417419;
4.sync,9.958417669;
4.sync,9.958417919;
4.sync,9.958418170;
[2022-04-24 18:28:36] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-04-24 18:28:36] [Connection 1]  Closing guacd connection
[2022-04-24 18:28:37] [Connection 1]  Client connection closed
rdpCreateScreenResources:
rdpmousePreInit: drv 0xaaaace73ba80 info 0xaaaace9ff500, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0xffff8be80c70
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0xaaaace73b250 info 0xaaaacea02680, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0xffff8be616e0
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1024 height 768
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 16
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0xaaaacea36e10
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1024 height 768 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0xffff8bce0000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1024 cy 768
rdpClientConProcessMsgClientInfo:
  got client info bytes 7072
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1024 height 768
rdpLoadLayout: keylayout 0x00000409 variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
(EE) Failed to open authorization file ".Xauthority": No such file or directory
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[993]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[993]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[993]: INFO:	Connected to RDPDR 1.12 as client 0x4a9dc7f3
guacd[993]: INFO:	RDPDR user logged on
guacd[993]: ERROR:	User is not responding.
guacd[993]: INFO:	User "@71fdc520-925f-4167-91a4-280bf4474857" disconnected (0 users remain)
guacd[993]: INFO:	Last user of connection "$42ccbcd0-599c-4a88-8bab-2a9677be0e07" disconnected
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0xaaaacea36e10
guacd[993]: INFO:	Internal RDP client disconnected
guacd[911]: INFO:	Connection "$42ccbcd0-599c-4a88-8bab-2a9677be0e07" removed.
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 16
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0xaaaacea36e10
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1874 height 977 bpp 32
rdpClientConProcessScreenSizeMsg: shmemid 1 shmemptr 0xffff80633000
rdpRRScreenSetSize: width 1874 height 977 mmWidth 496 mmHeight 258
rdpRRGetInfo:
  screen resized to 1874x977
rdpClientConProcessScreenSizeMsg: RRScreenSizeSet ok=[1]
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1874 cy 977
KbdSync: toggling num lock
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpClientConProcessMsgClientInfo:
  got client info bytes 7072
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1874 height 977
rdpRRUpdateOutput:
rdpLoadLayout: keylayout 0x0000040c variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
KbdSync: toggling num lock
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
rdpkeybBell:
```

**Comment by scottsuch** [comment]
I've got my local deployment pinned to 5.38.0 as that's the last release that seems to work for me. Thanks for filing this.

**Comment by alexbelgium** [comment]
I think I have the same observation : when I install the latest arm64v8-arch image on an rpi4, I don't see the webui. When I right click, go in xterm, and type "calibre", I get :
```
Traceback (most recent call last):
  File "/sbin/calibre", line 20, in <module>
    from calibre.gui_launch import calibre
  File "/usr/lib/calibre/calibre/__init__.py", line 22, in <module>
    initialize_calibre()
  File "/usr/lib/calibre/calibre/startup.py", line 124, in initialize_calibre
    from calibre.utils.icu import title_case, lower as icu_lower, upper as icu_upper
  File "/usr/lib/calibre/calibre/utils/icu.py", line 12, in <module>
    from calibre_extensions import icu as _icu
ImportError: libicui18n.so.71: cannot open shared object file: No such file or directory
```

**Comment by prahal** [comment]
tag [arm64v8-arch-version-a862938c](https://hub.docker.com/layers/calibre/linuxserver/calibre/arm64v8-arch-version-a862938c/images/sha256-3956a25a637c0a4dfe8ce17edd53386ce322388c62ff16e089e332cf020e4c53?context=explore) from March 7, 2022 for https://hub.docker.com/r/linuxserver/calibre fixes the missing libicu 71. Closing.
